Task3
JRRGomes/log-parser pull request #3
Opened 2022-01-24 12:26 UTC by JRRGomes

PR resolve a Tarefa 3 do desafio: 
https://gist.github.com/fabiosammy/5245c7e85796a7831d5f5f81c4103b21

2022-01-24 15:23 UTC, sosolidkk commented on lib/parser.rb
> +    raise "File doesn't exist" unless File.exist?(@file)
👏🏻

2022-01-24 15:33 UTC, sosolidkk requested changes

2022-01-24 15:33 UTC, sosolidkk commented on lib/parser.rb
>      @file = file
Não seria mais interessante renomear isso aqui para `filename`? Visto que é o nome do arquivo que você passa pra cá. Da maneira como tá, passa a impressão de que é o arquivo em si.

2022-01-24 15:33 UTC, sosolidkk commented on lib/parser.rb
> +    end
```suggestion
    players_arr = []

    data = File.open(@file, &:readlines)
    client_lines = data.grep(/.......ClientUserinfoChanged/)

    client_lines.each do |line|
      players_lines = line.split('n\\')[1]
      players_arr << players_lines.split('\\').first
    end
```
Eu dei uma leve refatorada no teu código (não testei, mas deve funcionar). Alguns pontos:

1. Seria interessante você dar uma lida a mais sobre `each` e `map`. Nãoa havia necessidade de usar map nesse caso, já que você queria somente iterar sobre as linhas (é pra isso que serve o each).
2. Declaração de variável é recomendado que seja sempre no início de um bloco (facilita a legibilidade)
3. Você criou algumas variáveis que eu achei um pouco desnecessárias dentro do bloco, então por isso de uma reduzida no código removendo algumas delas. Lembre-se que cada variável é um espaço na memória que você vai tá alocando, seja prudente com o uso delas kkkk
4. Você pode pegar o conteúdo de um arquivo e armazenar em uma variável e utilizar essa variável pra manipular o conteúdo. Vi que você abria o arquivo, pegava as linhas, ai alaterava um pouco e só depois fechava o arquivo. Não tem necessidade disso também. Fica a dica ai

2022-01-24 16:52 UTC, JRRGomes commented on lib/parser.rb
> +    raise "File doesn't exist" unless File.exist?(@file)
foi o Ruby Solagraph que me avisou  kkk

2022-01-25 16:26 UTC, sosolidkk commented on lib/parser.rb
> +    filename = File.foreach(@filename)
A nomeclatura escolhida para a variável não condiz com o que vai ser armazenado nela. É bom se atentar a isso.
```suggestion
    file_content = File.foreach(@filename)
```

2022-01-25 16:26 UTC, sosolidkk commented on lib/parser.rb
>      first_line
Mesmo comentário que fiz sobre a escolha do nome para variável nesse filename. Além disso, dá pra reduzir bastante a declaração de variáveis. Vale lembrar que cada variável é um endereço a mais que a gente vai consumir da memória, então é sempre bom levar em consideração se é necessário mesmo o uso delas ou não.

```suggestion
    File.open(@filename, &:readline)
```

2022-01-25 16:26 UTC, sosolidkk commented on lib/parser.rb
> +    JSON.pretty_generate({ @filename => { lines: file_lines, players: players_arr.uniq } })
```suggestion
    players_arr = []

    file_content = File.open(@filename, &:readlines)
    line_count = file_content.count

    client_lines = file_content.grep(/.......ClientUserinfoChanged/)

    client_lines.each do |line|
      players_lines = line.split('n\\')[1]
      players_arr << players_lines.split('\\').first
    end
    JSON.pretty_generate({ @filename => { lines: file_lines, players: players_arr.uniq } })
```

2022-01-25 16:26 UTC, sosolidkk commented on lib/parser.rb
> +    JSON.pretty_generate({ @filename => { lines: file_lines, players: players_arr.uniq } })
Só passando pra reforçar a declaração de variáveis ser sempre no início do bloco de uma função para ficar mais fácil encontrar o tipo da variável.

2022-01-25 17:15 UTC, merged